# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/easytraza?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# HTTPS / SSL CONFIGURATION (WEB)
# ===============================
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:certs/easytraza-keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=easytraza

# ===============================
# HTTP ADDITIONAL CONNECTOR (MOBILE)
# ===============================
server.http.port=8080

# ===============================
# OCR CONFIGURATION - TESSERACT
# ===============================
ocr.tessdata.path=C:/Program Files/Tesseract-OCR/tessdata
ocr.tesseract.language=spa+cat+eng
# OCR DOCUMENT STORAGE
ocr.documents.path=../uploads/albarans-proveidor/documents-ocr
perfil.fotos.path=../uploads/perfils

# ===================
# EMAIL
# ===================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testdam2025@gmail.com
spring.mail.password=yloq vely qsvc mthj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true